using System.Text;
using System.Net.Http.Json;
using PokemonBattle.Models;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

internal static class SpriteGroundCatalogGenerator
{
    private const int FirstPokemonId = 1;
    private const int LastPokemonId = 721;
    private const int AlphaThreshold = 0;

    public static async Task GenerateAsync(HttpClient http, string outputPath)
    {
        http.Timeout = TimeSpan.FromSeconds(30);
        var sources = new List<SpriteSource>();
        var failures = new List<string>();

        for (int id = FirstPokemonId; id <= LastPokemonId; id++)
        {
            try
            {
                var pokemon = await http.GetFromJsonAsync<PokeApiPokemon>($"https://pokeapi.co/api/v2/pokemon/{id}");
                if (pokemon == null)
                {
                    failures.Add($"#{id} (pokemon response missing)");
                    continue;
                }

                string frontUrl = CommunitySpriteOverrides.GetFrontUrl(pokemon.name)
                    ?? pokemon.sprites.other?.showdown?.front_default
                    ?? pokemon.sprites.front_default
                    ?? "";
                string backUrl = CommunitySpriteOverrides.GetBackUrl(pokemon.name)
                    ?? pokemon.sprites.other?.showdown?.back_default
                    ?? frontUrl;

                sources.Add(new SpriteSource(pokemon.name, frontUrl, backUrl));
                Console.WriteLine($"[sprite {id}/{LastPokemonId}] {pokemon.name} URL 준비");
            }
            catch (Exception ex)
            {
                failures.Add($"#{id} ({ex.GetType().Name}: {ex.Message})");
                Console.WriteLine($"[sprite {id}/{LastPokemonId}] API 실패: {ex.Message}");
            }
        }

        var frontRatios = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase);
        var backRatios = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase);
        using var semaphore = new SemaphoreSlim(12);
        var measurementTasks = sources.Select(async source =>
        {
            await semaphore.WaitAsync();
            try
            {
                var front = await MeasureAsync(http, source.Name, "front", source.FrontUrl);
                var back = await MeasureAsync(http, source.Name, "back", source.BackUrl);
                return new SpriteMeasurement(source.Name, front, back);
            }
            finally
            {
                semaphore.Release();
            }
        });

        foreach (var measurement in await Task.WhenAll(measurementTasks))
        {
            frontRatios[measurement.Name] = measurement.Front.Ratio;
            backRatios[measurement.Name] = measurement.Back.Ratio;
            if (measurement.Front.Failure != null) failures.Add(measurement.Front.Failure);
            if (measurement.Back.Failure != null) failures.Add(measurement.Back.Failure);
        }

        var generated = new StringBuilder();
        generated.AppendLine("namespace PokemonBattle.Models;");
        generated.AppendLine();
        generated.AppendLine("// Generated by DataGen/SpriteGroundCatalogGenerator.cs. Do not edit by hand.");
        generated.AppendLine("public static class PokemonSpriteGroundCatalog");
        generated.AppendLine("{");
        AppendDictionary(generated, "FrontRatios", frontRatios);
        AppendDictionary(generated, "BackRatios", backRatios);
        generated.AppendLine();
        var distinctFailures = failures
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(value => value, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        if (distinctFailures.Length == 0)
        {
            generated.AppendLine("    public static readonly IReadOnlyList<string> MeasurementFailures = Array.Empty<string>();");
        }
        else
        {
            generated.AppendLine("    public static readonly IReadOnlyList<string> MeasurementFailures = new[]");
            generated.AppendLine("    {");
            foreach (string failure in distinctFailures)
            {
                generated.AppendLine($"        \"{Escape(failure)}\",");
            }
            generated.AppendLine("    };");
        }
        generated.AppendLine();
        generated.AppendLine("    public static double GroundOffsetRatioFor(string englishName, bool back)");
        generated.AppendLine("    {");
        generated.AppendLine("        var catalog = back ? BackRatios : FrontRatios;");
        generated.AppendLine("        return catalog.TryGetValue(englishName, out double ratio) ? ratio : 0;");
        generated.AppendLine("    }");
        generated.AppendLine();
        generated.AppendLine("    public static bool HasMeasurementFor(string englishName, bool back)");
        generated.AppendLine("    {");
        generated.AppendLine("        var catalog = back ? BackRatios : FrontRatios;");
        generated.AppendLine("        return catalog.ContainsKey(englishName);");
        generated.AppendLine("    }");
        generated.AppendLine("}");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");
        await File.WriteAllTextAsync(outputPath, generated.ToString());
        Console.WriteLine($"스프라이트 지면 카탈로그 완료: {frontRatios.Count}종, 실패 {failures.Count}건");
        if (failures.Count > 0)
        {
            Console.WriteLine("측정 실패 목록:");
            foreach (string failure in failures.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(value => value, StringComparer.OrdinalIgnoreCase))
            {
                Console.WriteLine($"  - {failure}");
            }
        }
    }

    private static async Task<MeasurementResult> MeasureAsync(
        HttpClient http,
        string pokemonName,
        string side,
        string url)
    {
        try
        {
            if (string.IsNullOrWhiteSpace(url))
            {
                throw new InvalidOperationException("sprite URL is empty");
            }

            byte[] content = await http.GetByteArrayAsync(url);
            return new MeasurementResult(MeasureBottomTransparentRatio(content), null);
        }
        catch (Exception ex)
        {
            string failure = $"{pokemonName} ({side}: {ex.GetType().Name}: {ex.Message})";
            Console.WriteLine($"[sprite] {failure}");
            return new MeasurementResult(0, failure);
        }
    }

    private static double MeasureBottomTransparentRatio(byte[] content)
    {
        using Image<Rgba32> image = Image.Load<Rgba32>(content);
        ImageFrame<Rgba32> frame = image.Frames[0];
        int lowestVisibleRow = -1;

        for (int y = 0; y < frame.Height; y++)
        {
            for (int x = 0; x < frame.Width; x++)
            {
                if (frame[x, y].A > AlphaThreshold)
                {
                    lowestVisibleRow = y;
                }
            }
        }

        if (lowestVisibleRow < 0)
        {
            throw new InvalidDataException("image has no visible pixels");
        }

        return Math.Clamp((frame.Height - 1 - lowestVisibleRow) / (double)frame.Height, 0, 1);
    }

    private static void AppendDictionary(StringBuilder output, string name, IReadOnlyDictionary<string, double> values)
    {
        output.AppendLine($"    private static readonly IReadOnlyDictionary<string, double> {name} = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase)");
        output.AppendLine("    {");
        foreach (var (key, value) in values.OrderBy(pair => pair.Key, StringComparer.OrdinalIgnoreCase))
        {
            output.AppendLine($"        [\"{Escape(key)}\"] = {value.ToString("0.######", System.Globalization.CultureInfo.InvariantCulture)},");
        }
        output.AppendLine("    };");
    }

    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed record SpriteSource(string Name, string FrontUrl, string BackUrl);
    private sealed record SpriteMeasurement(string Name, MeasurementResult Front, MeasurementResult Back);
    private sealed record MeasurementResult(double Ratio, string? Failure);
}